### ISSUE TITLE
Typo in debug statement

### ISSUE THREAD

**Issue by briancherin** [ericcherin/ebayPriceFinder#1]
https://github.com/ericcherin/ebayPriceFinder/blob/cb46c31d67b0e778d2bcb0cec2dfb34a58462425/src/lat/EbayApi.cs#L22

**Expected Behavior**
Should say "get response 1" so that the statement is more clear.

**Incorrect Behavior**
Says "get respinse 1". This is very confusing.

**Comment by ericcherin** [comment]
Wow, this code is awful! Who wrote this? Run while you still can, folks.

I will close this because I like closing things. There are more severe issues in this code than a typo. In EbayApi.cs I exposed the client secret. A classic mistake.
